---

- name: Installing and configuring Docker registry
  hosts: "Server"
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: docker-registry, tags: ["docker-registry"] }
