---

- name: Installing and configuring dpcore-module-cloudsearch
  hosts: Server
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: docker-core-cs, tags: ["docker-core-cs"] }
