---

- name: Installing and configuring dpcore-module-cloudsearch-scripts
  hosts: Server
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: docker-cs-scripts, tags: ["docker-cs-scripts"] }
