---

- name: Installing and configuring dpcore-module-oauth
  hosts: Server
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: docker-core-oauth, tags: ["docker-core-oauth"] }
