---

- name: Installing and configuring dpcore-module-api
  hosts: Server
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: docker-core-api, tags: ["docker-core-api"] }
