---

- name: Installing and configuring Docker
  hosts: "Server"
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: rancher-server, tags: ["rancher-server"] }
