---

- name: Installing and configuring Docker
  hosts: Server:Agents
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: docker, tags: ["docker"] }


- name: Install Docker-registry and registry-web
  hosts: "Server"
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: docker-registry, tags: ["docker-registry"] }

- name: Install Rancher server and push docker images to docker-registry
  hosts: "Server"
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: rancher-server, tags: ["rancher-server"] }


- name: Install Rancher Agents
  hosts: "Agents"
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: rancher-nodes, tags: ["rancher-node"] }

- name: Install Rancher CLI
  hosts: Server
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: rancher-cli, tags: ["rancher-cli"] }

- name: Copy mariadb-cs dump file
  hosts: Agents
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  tasks:
    - name: Create temporary directory to save rancher compose file
      file: path="{{ remote_temp_directory }}/{{ mariadb_data_folder }}" state=directory mode=0755

    - name: Copy db dump file
      copy:
        src: "data/{{ mariadb_data_folder }}"
        dest: "{{ remote_temp_directory }}"
        mode: 0777
        force: no

- name: Deploy mariadb conainer using rancher cli
  hosts: Server
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: docker-db, tags: ["docker-db"] }

- name: Deploy dpcore-module-cloudsearch  & scripts conainers using rancher cli
  hosts: Server
  gather_facts: no
  vars_files:
   - inventories/group_vars/main.yml
  roles:
   - { role: docker-core-cs, tags: ["docker-core-cs"] }


#
# - name: Deploy dpcore-module-cloudsearch-scripts conainer using rancher cli
#   hosts: Server
#   gather_facts: no
#   vars_files:
#    - inventories/group_vars/main.yml
#   roles:
#    - { role: docker-cs-scripts, tags: ["docker-cs-scripts"] }
