---

- name: Install Rancher Server
  hosts: "Server"
  gather_facts: no
  vars_files:
    - inventories/group_vars/main.yml
  tasks:

  - name: Set some kernel parameters
    lineinfile:
      dest: /etc/hosts
      line: "{{ item }}"
      # regexp:  "{{ item }}"
      # backrefs: yes
    with_items: "{{ hosts_items }}"
    become: true

  # - name: Test connections
  #   shell: ls -al
  #   register: output_msg
  #
  #
  # - name: Print results
  #   debug: msg="{{ output_msg }}"

# - name: copy server's public key to agent server
#   hosts: all
#   vars_files:
#     - inventories/group_vars/main.yml
#   roles:
#     - { role: copy-ssh-id }
