---


- name: Add user(dpcore)
  hosts: all
  gather_facts: no
  vars_files:
    - inventories/group_vars/main.yml
  vars:
     # created with:
     # python -c 'import crypt; print crypt.crypt("hadoop1234", "$1$SomeSalt$")'
    password: $1$SomeSalt$Nr4pB1yhv/M4Is8EsMBMJ1
  tasks:

  - name: Create a login user
    user:
      name: "{{ dpcore_user }}"
      password: "{{ password }}"
      groups: wheel  # Empty by default.
      state: present
      # disabled-password: true
    become: yes

  - name: Add user to sudoers file
    lineinfile:
      path: /etc/sudoers
      regexp: '^ansibleuser'
      line: '{{ dpcore_user }} ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
    become: yes

  - name: Copy system shell to all host
    copy:
      src: "data/system/docker_lvcreate.sh"
      dest: "/home/{{ remote_user }}/docker_lvcreate.sh"
      mode: 0777
      force: no


  - name: check the current config values
    shell: cat /etc/sysctl.conf | grep net.ipv4.ip_forward
    register: current_ipv4
    check_mode: no
    ignore_errors: yes
    become: yes

  - name: print if ip_forward value is already changed
    debug: var=current_ipv4.stdout

  - name: modify sysctl ipv4 config
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
    become: yes

  - name: check if the config changed correctly
    shell: cat /etc/sysctl.conf
    register: ipv4
    failed_when: "'net.ipv4.ip_forward=1' not in ipv4.stdout"
    become: yes
