---

- name: Install Rancher Server
  hosts: "AWS"
  gather_facts: no
  vars_files:
    - inventories/group_vars/main.yml
  vars:
     # created with:
     # python -c 'import crypt; print crypt.crypt("freepsw", "$1$SomeSalt$")'
    password: $1$SomeSalt$cb7pl7OwHhez6RBCGnxjL1
  tasks:

  - name: Create a login user
    user:
      name: "{{ remote_user }}"
      password: "{{ password }}"
      groups: wheel  # Empty by default.
      state: present
      disabled-password: true
    become: yes

  - name: Add user to sudoers file
    lineinfile:
      path: /etc/sudoers
      regexp: '^ansibleuser'
      line: '{{ remote_user }} ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
    become: yes

  # - name: Commenting a line using the regualr expressions in Ansible.
  #   replace:
  #     path: /etc/hosts
  #     regexp: '(.*rancher\.server)'
  #     replace: '#\1'
  #     backup: yes
  #   become: true
  #
  # - name: Commenting a line using the regualr expressions in Ansible.
  #   replace:
  #     path: /etc/hosts
  #     regexp: '(.*docker\.registry\.server)'
  #     replace: '#\1'
  #     backup: yes
  #   become: true

  # - name: Commenting a line using the regualr expressions in Ansible.
  #   replace:
  #     path: /etc/hosts
  #     regexp: 'registry\.server'
  #     replace: '#\1'
  #     backup: yes
      # regexp: '(*.server.*)'
      # replace: '#\1'

  # - name: Set some kernel parameters
  #   lineinfile:
  #     dest: /etc/hosts
  #     line: "{{ item }}"
  #     # regexp:  "{{ item }}"
  #     # backrefs: yes
  #   with_items: "{{ hosts_items }}"
  #   become: true

  - name: Test connections
    shell: ls -al
    register: output_msg


  - name: Print results
    debug: msg="{{ output_msg }}"

# - name: copy server's public key to agent server
#   hosts: all
#   vars_files:
#     - inventories/group_vars/main.yml
#   roles:
#     - { role: copy-ssh-id }
