---

# - name: Set facts
#   set_fact:
#     mariadb_compose_files_folder: "{{ remote_temp_directory }}/docker-db/compose-files"

- name: Create temporary directory to save rancher compose file
  file: "path={{ item }} state=directory mode=0755"
  with_items:
  - "{{ mariadb_compose_files_folder }}/{{ mariadb_dump_cs_folder }}"
  - "{{ mariadb_compose_files_folder }}/{{ mariadb_dump_sso_folder }}"


# Mariadb for cloudsearch
# - name: Copy docker/rancher-compose file for cloudserach database
#   template:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     mode: 0644
#   with_items:
#     - {src: 'templates/{{ mariadb_dump_cs_folder }}/docker-compose.yml.j2',  dest: '{{ mariadb_compose_files_folder }}/{{ mariadb_dump_cs_folder }}/docker-compose.yml'}
#     - {src: 'templates/{{ mariadb_dump_cs_folder }}/rancher-compose.yml.j2', dest: '{{ mariadb_compose_files_folder }}/{{ mariadb_dump_cs_folder }}/rancher-compose.yml'}
#
# - name: Run ranche cli for mariadb container (Cloudsearch)
#   shell: "{{ remote_temp_directory }}/rancher/rancher --env Default up -s meta-db -d"
#   args:
#     chdir: "{{ mariadb_compose_files_folder }}/{{ mariadb_dump_cs_folder }}"


# Mariadb for sso
- name: Copy docker/rancher-compose file for cloudserach database
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - {src: 'templates/{{ mariadb_dump_sso_folder }}/docker-compose.yml.j2',  dest: '{{ mariadb_compose_files_folder }}/{{ mariadb_dump_sso_folder }}/docker-compose.yml'}
    - {src: 'templates/{{ mariadb_dump_sso_folder }}/rancher-compose.yml.j2', dest: '{{ mariadb_compose_files_folder }}/{{ mariadb_dump_sso_folder }}/rancher-compose.yml'}

- name: Run ranche cli for mariadb container (SSO)
  shell: "{{ remote_temp_directory }}/rancher/rancher --env Default up -s meta-db -d"
  args:
    chdir: "{{ mariadb_compose_files_folder }}/{{ mariadb_dump_sso_folder }}"



# - name: Run mariadb container
#   docker:
#     image: mariadb:10.3
#     name: mariadb
#     ports: "{{ mariadb_port }}:3306"
#     volumes:
#       - "{{ remote_temp_directory }}/db/{{ mariadb_dump_file }}:/docker-entrypoint-initdb.d/dpcore_search.sql"
#     pull: missing
#     restart_policy: unless-stopped
#     state: started
#     env:
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_DATABASE: dpcore_search
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
