---

- name: Create temporary directory to save rancher compose file
  file: path="{{ remote_temp_directory }}/mariadb" state=directory mode=0755

- name: Copy db dump file
  copy:
    src: "{{ mariadb_data_folder }}"
    dest: "{{ remote_temp_directory }}"
    force: no

- name: Copy docker/rancher-compose file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - {src: 'templates/docker-compose.yml.j2',  dest: '{{ remote_temp_directory }}/mariadb/docker-compose.yml'}
    - {src: 'templates/rancher-compose.yml.j2', dest: '{{ remote_temp_directory }}/mariadb/rancher-compose.yml'}


#
- name: Run ranche cli for mariadb container
  shell: "{{ remote_temp_directory }}/rancher/rancher --env Default up -s meta-db -d"
  args:
    chdir: "{{ remote_temp_directory }}/mariadb"




# - name: Run mariadb container
#   docker:
#     image: mariadb:10.3
#     name: mariadb
#     ports: "{{ mariadb_port }}:3306"
#     volumes:
#       - "{{ remote_temp_directory }}/db/{{ mariadb_dump_file }}:/docker-entrypoint-initdb.d/dpcore_search.sql"
#     pull: missing
#     restart_policy: unless-stopped
#     state: started
#     env:
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_DATABASE: dpcore_search
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
