---

# - name: Copy ansible related files
#   copy:
#     src: "data/docker-cs-scripts/"
#     dest: "{{ remote_temp_directory }}"
#     force: no

- name: Create temporary directory to save rancher compose file
  file: path="{{ remote_temp_directory }}/dpcore-cs-scripts" state=directory mode=0755

- name: Copy docker-compose / rancher-compose files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - {src: 'templates/rancher/docker-compose.yml.j2',  dest: '{{ remote_temp_directory }}/dpcore-cs-scripts/docker-compose.yml'}
    - {src: 'templates/rancher/rancher-compose.yml.j2', dest: '{{ remote_temp_directory }}/dpcore-cs-scripts/rancher-compose.yml'}

- name: Run ranche cli for dpcore-module-cloudsearc-scripts container
  shell: "{{ remote_temp_directory }}/rancher/rancher --env Default up -s dpcore -d"
  args:
    chdir: "{{ remote_temp_directory }}/dpcore-cs-scripts/"
