---

# Common
dpcore_user: dpcore
dpcore_password: 1234qwer
remote_user: 'freepsw_02'
remote_temp_directory: "/home/{{ remote_user }}/temp"
rancher_server_host_name: rancher.server
docker_registry_host_name: docker.registry.server

hosts_items:
  - "{{ hostvars['server1'].ansible_ssh_host }} {{ rancher_server_host_name }}"
  - "{{ hostvars['server1'].ansible_ssh_host }} {{ docker_registry_host_name }}"


# Rancher
rancher_server_version: "v1.6.23"
rancher_agent_version: "v1.2.11"
rancher_name: "rancher_server"
rancher_agent_name: "rancher_agent"
rancher_ip: "{{ hostvars['server1'].ansible_ssh_host }}"
rancher_port: 8080

rancher_server_image: "racher_server.tar.gz"
rancher_agent_image: "racher_agent.tar.gz"

rancher_access_key: 3AACFC1293B14DA44B15
rancher_secret_key: cdGzqLfXRXtAqjxDXyt6pCcFejNqLpfbKNEn7cWJ


# docker-ce version
docker_data_folder: data/docker/

docker_image_file_folder: data/images/
docker_repo_file: docker-ce.repo
docker_rpm_file: docker-ce-17.12.1.ce-1.el7.centos.x86_64.rpm

# docker registry
docker_registry_image: docker-registry.tar.gz
docker_registry_data_directory: /home/{{ remote_user }}/docker-registry-images
docker_registry_expose_port: 5000
docker_registry_url: "{{ docker_registry_host_name }}:{{ docker_registry_expose_port }}"

# docker registry web
docker_registry_web_name: registry-web
docker_registry_web_image: docker-registry-web.tar.gz
docker_registry_web_expose_port: 8081

#docker_registry_url: "myb"

# mariadb
mariadb_ip: "{{ hostvars['agent1'].ansible_ssh_host }}"
mariadb_port: 3308
mariadb_dump_file: dpcore_search_dump.sql
mariadb_data_folder: data/db
mairadb_image: docker-mariadb-10-3.tar.gz
mairadb_rancher_label: io.rancher.host.os=linux
mariadb_user: cloudsearch
mariadb_password: '!cloudsearch00'

# dpcore-cloudsearch
dpcore_log_folder: /data/log_data/
dpcore_rancher_label: io.rancher.host.os=linux
dpcore_cloudsearch_image: core-module-cloudsearch.tar.gz
## dpcore-cloudsearh

# dpcore-cloudsearch-ansible
dpcore_cloudsearch_ansible_image: core-module-cloudsearch-ansible.tar.gz
dpcore_cloudsearch_ansible_file: cloudsearch.scripts.tgz
dpcore_cloudsearch_ansible_folder: /home/dpcore/data-api-svc/core-module-cloudsearch-1.0-SNAPSHOT/script
