---

# Common
remote_user: 'freepsw_02'
remote_temp_directory: "/home/{{ remote_user }}/temp"

# Rancher
rancher_server_version: "v1.6.23"
rancher_agent_version: "v1.2.11"
rancher_name: "rancher_server"
rancher_agent_name: "rancher_agent"
rancher_ip: "{{ hostvars['server1'].ansible_ssh_host }}"
rancher_port: 8080

rancher_server_image: "racher_server.tar.gz"
rancher_agent_image: "racher_agent.tar.gz"

rancher_access_key: A0B9A7F77402D7B253D1
rancher_secret_key: aJx6x9976D2qnBVaZrLBUqF8p7ZiNG6HbV9baV43


# docker-ce version
docker_data_folder: data/docker/

docker_image_file_folder: data/images/
docker_repo_file: docker-ce.repo
docker_rpm_file: docker-ce-17.12.1.ce-1.el7.centos.x86_64.rpm

# docker registry
docker_registry_image: docker-registry.tar.gz
docker_registry_data_directory: /home/{{ remote_user }}/docker-registry-images
docker_registry_expose_port: 5000
docker_registry_url: "{{ hostvars['server1'].ansible_ssh_host }}:{{ docker_registry_expose_port }}"

# docker registry web
docker_registry_web_name: registry-web
docker_registry_web_image: docker-registry-web.tar.gz
docker_registry_web_expose_port: 8081

#docker_registry_url: "myb"

# mariadb
mariadb_port: 3306
mariadb_dump_file: dpcore_search_dump.sql
mariadb_data_folder: data/db
