---

# Common
dpcore_user: dpcore
dpcore_password: 1234qwer
remote_user: 'dpcore'
remote_temp_directory: "/home/{{ remote_user }}/temp"
rancher_server_host_name: rancher.server
docker_registry_host_name: docker.registry.server
# docker_registry_host_name: registry.accuinsight.io

hosts_items:
  - "{{ hostvars['server1'].ansible_ssh_host }} {{ rancher_server_host_name }}"
  - "{{ hostvars['server1'].ansible_ssh_host }} {{ docker_registry_host_name }}"
hosts_rancher_label: "io.rancher.host.os=linux"

# Rancher
rancher_server_version: "v1.6.23"
rancher_agent_version: "v1.2.11"
rancher_name: "rancher_server"
rancher_agent_name: "rancher_agent"
rancher_ip: "{{ hostvars['server1'].ansible_ssh_host }}"
rancher_port: 8080

rancher_server_image: "racher_server.tar.gz"
rancher_agent_image: "racher_agent.tar.gz"
rancher_agents_images:
  - file: rancher_net-v0.13.tar.gz
    name: rancher/net:v0.13.17
    image: "{{ docker_registry_url}}/rancher/net:v0.13.17"
  - file: rancher_net-holder.tar.gz
    name: rancher/net:holder
    image: "{{ docker_registry_url}}/rancher/net:holder"
  - file: rancher_dns.tar.gz
    name: rancher/dns:v0.17.4
    image: "{{ docker_registry_url}}/rancher/dns:v0.17.4"
  - file: rancher_scheduler.tar.gz
    name: rancher/scheduler:v0.8.5
    image: "{{ docker_registry_url}}/rancher/scheduler:v0.8.5"
  - file: rancher_healthcheck.tar.gz
    name: rancher/healthcheck:v0.3.8
    image: "{{ docker_registry_url}}/rancher/healthcheck:v0.3.8"
  - file: rancher_metadata.tar.gz
    name: rancher/metadata:v0.10.4
    image: "{{ docker_registry_url}}/rancher/metadata:v0.10.4"
  - file: rancher_network-manager.tar.gz
    name: rancher/network-manager:v0.7.22
    image: "{{ docker_registry_url}}/rancher/network-manager:v0.7.22"

rancher_access_key: 3AACFC1293B14DA44B15
rancher_secret_key: cdGzqLfXRXtAqjxDXyt6pCcFejNqLpfbKNEn7cWJ


# docker-ce version
docker_data_folder: data/docker/

docker_image_file_folder: data/images/
docker_repo_file: docker-ce.repo
docker_rpm_file: docker-ce-17.12.1.ce-1.el7.centos.x86_64.rpm

# docker registry
docker_registry_image: docker-registry.tar.gz
docker_registry_data_directory: /home/{{ remote_user }}/docker-registry-images
docker_registry_expose_port: 5000
docker_registry_url: "{{ docker_registry_host_name }}:{{ docker_registry_expose_port }}"

# docker registry web
docker_registry_web_name: registry-web
docker_registry_web_image: docker-registry-web.tar.gz
docker_registry_web_expose_port: 8081

#docker_registry_url: "myb"

# mariadb
mariadb_ip: "{{ hostvars['agent1'].ansible_ssh_host }}"
mariadb_sso_port: 3307
mariadb_cs_port: 3308
mariadb_data_folder: docker-db
mariadb_dump_cs_folder: core-cs
mariadb_dump_sso_folder: core-sso
mariadb_compose_files_folder: "{{ remote_temp_directory }}/{{ mariadb_data_folder }}/compose-folder"
mairadb_image: docker-mariadb-10-3.tar.gz
mairadb_rancher_label: backend=01
mariadb_cs_user: cloudsearch
mariadb_cs_password: '!cloudsearch00'

# dpcore-cloudsearch
dpcore_log_folder: /data/log_data
dpcore_log_module_folder:
  - core-sso-server
  - core-oauth-server
  - core-module-cloudsearch
  - core-api-gateway
dpcore_compose_files_folder: "{{ remote_temp_directory }}/core-modules/compose-folder"
dpcore_rancher_label: backend=01
dpcore_cloudsearch_image: core-module-cloudsearch.tar.gz
dpcore_elasticsearch_images:
  - file: docker-es.tar.gz
    image: "{{ docker_registry_url}}/dpcore/es-gotty:6.3.1"
  - file: docker-es-hq.tar.gz
    image: "{{ docker_registry_url}}/dpcore/elasticsearch-hq:3.4.1"
  - file: docker-kibana.tar.gz
    image: "{{ docker_registry_url}}/dpcore/kibana-gotty:6.3.1"
# dpcore_elasticsearch_image_name: "{{ docker_registry_url}}/dpcore/es-gotty:6.3.1"
# dpcore_elasticsearch_kibana_name: "{{ docker_registry_url}}/dpcore/kibana-gotty:6.3.1"
# dpcore_elasticsearch_hq_name: "{{ docker_registry_url}}/dpcore/elasticsearch-hq:3.4.0"

## dpcore-cloudsearh

# dpcore-cloudsearch-scripts
dpcore_cloudsearch_scripts_image: core-module-cloudsearch-scripts.tar.gz
dpcore_cloudsearch_scripts_image_name: dpcore/core-module-cloudsearch-scripts


## dpcore-sso module
dpcore_sso_folder: core-sso-server
dpcore_sso_images:
  - file: core-module-sso.tar.gz
    image: "{{ docker_registry_url}}/dpcore/core-sso-server:stg02"


## dpcore-oauth module
dpcore_oauth_folder: core-oauth-server
dpcore_oauth_images:
  - file: core-module-oauth.tar.gz
    image: "{{ docker_registry_url}}/dpcore/core-oauth-server:stg02"

## dpcore-api module
dpcore_api_folder: core-sso-server
dpcore_api_images:
  - file: core-module-api.tar.gz
    image: "{{ docker_registry_url}}/dpcore/core-api-gateway:stg02"


## dpcore-web-cs frontend
dpcore_web_cs_folder: web-module-cs
dpcore_web_cs_images:
  - file: web-module-cs.tar.gz
    image: "{{ docker_registry_url}}/dpcore/cloudsearch-nginx-stg"
