---

- name: Comment out existing rancher.server ip
  replace:
    path: /etc/hosts
    regexp: '(.*rancher\.server)'
    replace: '#\1'
    backup: yes
  become: true

- name:  Comment out existing docker.registry.server ip
  replace:
    path: /etc/hosts
    regexp: '(.*docker\.registry\.server)'
    replace: '#\1'
    backup: yes
  become: true

- name: Add host name and ip to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ item }}"
  with_items: "{{ hosts_items }}"
  become: true


# - name: Increase file descriptor count to 70000
#   lineinfile:
#     dest: /etc/security/limits.conf
#     backup: yes
#     line: "{{ item.line }}"
#   with_items:
#     - { line: '* hard nofile 70000' }
#     - { line: '* soft nofile 70000' }
#     - { line: '* root hard 70000' }
#     - { line: '* hard nofile 70000' }
#   become: true
#
# - name: Increase nmap count to 262144
#   lineinfile:
#     dest: /etc/sysctl.conf
#     backup: yes
#     line: "{{ item.line }}"
#   with_items:
#     - { line: 'vm.max_map_count = 262144' }
#   become: true
#
# - name: Increase nmap count to 262144 with commmand
#   shell: sysctl -p
#   become: true
