---

- name: Copy rancher/server images file to ~/home/user/temp directory
  copy:
    src: "{{ docker_image_file_folder }}/{{ rancher_server_image }}"
    dest: "{{ remote_temp_directory }}"
    force: no

- name: Load image from archive and push to a private registry
  docker_image:
    name: "rancher/server"
    repository: "{{ docker_registry_url }}/rancher/server"
    tag: "{{ rancher_server_version }}"
    push: yes
    load_path: "{{ remote_temp_directory }}/{{ rancher_server_image }}"


- name: Run the Rancher/server contianer
  docker_container:
      name: "{{ rancher_name }}"
      image: "{{ docker_registry_url }}/rancher/server:{{ rancher_server_version }}"
      restart_policy: always
      ports:
        - "{{ rancher_port }}:8080"

- name: Wait for the Rancher server to start
  action: command docker logs {{ rancher_name }}
  register: rancher_logs
  until: rancher_logs.stdout.find("Listening on") != -1
  retries: 300
  delay: 5

- name: Print Rancher's URL
  debug: msg="You can connect to rancher server http://{{ rancher_ip }}:{{ rancher_port }}"
