---

- name: Copy rancher/server images file to ~/home/user/temp directory
  copy:
    src: "{{ docker_image_file_folder }}/{{ rancher_server_image }}"
    dest: "{{ remote_temp_directory }}"
    force: no

- name: Load rancher/server image from archive
  docker_image:
    name: rancher/server
    load_path: "{{ remote_temp_directory }}/{{ rancher_server_image }}"

- name: Run the Rancher/server contianer
  docker_container:
      name: "{{ rancher_name }}"
      image: rancher/server:{{ rancher_server_version }}
      restart_policy: always
      ports:
        - "{{ rancher_port }}:8080"

- name: Wait for the Rancher server to start
  action: command docker logs {{ rancher_name }}
  register: rancher_logs
  until: rancher_logs.stdout.find("Listening on") != -1
  retries: 300
  delay: 5

- name: Print Rancher's URL
  debug: msg="You can connect to rancher server http://{{ rancher_ip }}:{{ rancher_port }}"
