---

- name: Copy rancher/agent image file to ~/home/user/temp directory
  copy:
    src: "{{ docker_image_file_folder }}/{{ rancher_agent_image }}"
    dest: "{{ remote_temp_directory }}"
    force: no


- name: Load image from archive and push to a private registry
  docker_image:
    name: "rancher/agent"
    repository: "{{ docker_registry_url }}/rancher/agent"
    tag: "{{ rancher_agent_version }}"
    push: yes
    load_path: "{{ remote_temp_directory }}/{{ rancher_agent_image }}"
  become: true


- name: Copy rancher/server image file to ~/home/user/temp directory
  copy:
    src: "{{ docker_image_file_folder }}/{{ rancher_server_image }}"
    dest: "{{ remote_temp_directory }}"
    force: no

- name: Load rancher/server image from archive and push to a private registry
  docker_image:
    name: "rancher/server"
    repository: "{{ docker_registry_url }}/rancher/server"
    tag: "{{ rancher_server_version }}"
    push: yes
    load_path: "{{ remote_temp_directory }}/{{ rancher_server_image }}"
  become: true

- name: Copy mariadb image file to ~/home/user/temp directory
  copy:
    src: "{{ docker_image_file_folder }}/{{ mairadb_image }}"
    dest: "{{ remote_temp_directory }}"
    force: no

- name: Load mariadb image from archive and push to a private registry
  docker_image:
    name: "mariadb"
    repository: "{{ docker_registry_url }}/mariadb:10.3"
    tag: "10.3"
    push: yes
    load_path: "{{ remote_temp_directory }}/{{ mairadb_image }}"
  become: true


- name: Copy dpcore-module-cloudsearch image file to ~/home/user/temp directory
  copy:
    src: "{{ docker_image_file_folder }}/{{ dpcore_image }}"
    dest: "{{ remote_temp_directory }}"
    force: no

- name: Load dpcore-module-cloudsearch image from archive and push to a private registry
  docker_image:
    name: "docker-repo:5000/dpcore/core-module-cloudsearch"
    repository: "{{ docker_registry_url }}/dpcore/core-module-cloudsearch"
    push: yes
    load_path: "{{ remote_temp_directory }}/{{ dpcore_image }}"
  become: true
