---

# - name: Create Docker registry docroot.
#   file:
#     state: directory
#     path: "{{ docker_registry_data_directory }}"
#     mode: "0755"

- name: Copy docker-registry images file to ~/home/user/temp/docker directory
  copy:
    src: "{{ docker_image_file_folder }}/{{ docker_registry_image }}"
    dest: "{{ remote_temp_directory }}"
    force: no

- name: Pause 2 seconds to wait until copying image
  pause:
    seconds: 2

- name: Load docker-registry image from archive
  docker_image:
    name: registry
    tag: 2
    load_path: "{{ remote_temp_directory }}/{{ docker_registry_image }}"

- name: Run docker registry container
  docker:
    expose: "{{ docker_registry_expose_port }}"
    image: "registry:2"
    name: registry-srv
    ports: "{{ docker_registry_expose_port }}:{{ docker_registry_expose_port }}"
    # volumes:
    #   - "{{ docker_registry_data_directory }}:{{ docker_registry_data_directory }}"
    pull: missing
    restart_policy: unless-stopped
    # "reloaded" does not appear to be idempotent
    state: started
    # env:
    #   REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "{{ docker_registry_data_directory }}"

- name: Wait for Docker Registry to start
  uri:
    url: http://localhost:5000/v2/
    status_code: 200
    return_content: yes
  register: test_docker_registry
  until: test_docker_registry.content == '{}'
  retries: 10
  delay: 2
  ignore_errors: yes

- name: Print Docker-registry's URL
  debug: msg="You can connect to docker-registry http://{{ docker_registry_url }}"


- name: Copy docker-registry-web image file to ~/home/user/temp/docker directory
  copy:
    src: "{{ docker_image_file_folder }}/{{ docker_registry_web_image }}"
    dest: "{{ remote_temp_directory }}"
    force: no

- name: Load docker-registry-web image from archive
  docker_image:
    name: hyper/docker-registry-web
    tag: 2
    load_path: "{{ remote_temp_directory }}/{{ docker_registry_web_image }}"

- name: Run docker registry web container
  docker:
    expose: 8080
    image: hyper/docker-registry-web
    name: registry-web
    ports: "{{ docker_registry_web_expose_port }}:8080"
    links:
    - "registry-srv"
    pull: missing
    restart_policy: unless-stopped
    # "reloaded" does not appear to be idempotent
    state: started
    env:
      REGISTRY_URL: "http://registry-srv:5000/v2"
      REGISTRY_NAME: private-dockerhub
